export const genres = new Set([
    "Rock",
    "Electronic",
    "Pop",
    "Folk, World, & Country",
    "Jazz",
    "Funk / Soul",
    "Classical",
    "Latin",
    "Stage & Screen",
    "Reggae",
    "Non-Music",
    "Children\'s",
    "Brass & Military",
])