export const styles = [
    "Pop Rock",
    "House",
    "Vocal",
    "Experimental",
    "Punk",
    "Synth-pop",
    "Alternative Rock",
    "Techno",
    "Disco",
    "Soul",
    "Indie Rock",
    "Hardcore",
    "Ambient",
    "Folk",
    "Hard Rock",
    "Country",
    "Ballad",
    "Electro",
    "Rock & Roll",
    "Chanson",
    "Trance",
    "Heavy Metal",
    "Psychedelic Rock",
    "Downtempo",
    "Folk Rock",
    "Classic Rock",
    "Soundtrack",
    "Romantic",
    "Noise",
    "Prog Rock",
    "Schlager",
    "Funk",
    "Easy Listening",
    "Tech House",
    "Black Metal",
    "New Wave",
    "Blues Rock",
    "Deep House",
    "Rhythm & Blues",
    "Industrial",
    "Euro House",
    "Drum n Bass",
    "Death Metal",
    "Progressive House",
    "Classical",
    "Soft Rock",
    "Abstract",
    "Garage Rock",
    "Minimal",
    "Europop",
    "Acoustic",
    "Gospel",
    "Thrash",
    "Swing",
    "Big Band",
    "Baroque",
    "Dub",
    "Modern",
    "RnB/Swing",
    "Country Rock",
    "Breakbeat",
    "Contemporary Jazz",
    "Progressive Trance",
    "Drone",
    "Dancehall",
    "Indie Pop",
    "Opera",
    "IDM",
    "Breaks",
    "Contemporary",
    "Reggae",
    "Art Rock",
    "African",
    "Fusion",
    "Hard Trance",
    "Dark Ambient",
    "Avantgarde",
    "Doom Metal",
    "Gangsta",
    "Pop Rap",
    "Rockabilly",
    "Post-Punk",
    "Roots Reggae",
    "Beat",
    "Religious",
    "Jazz-Funk",
    "Electro House",
    "Acid",
    "Lo-Fi",
    "Instrumental",
    "Comedy",
    "Score",
    "Leftfield",
    "Grindcore",
    "Ska",
    "Dubstep",
    "Dance-pop",
    "Soul-Jazz",
    "Theme",
    "Post Rock",
    "Hip Hop",
    "Psy-Trance",
    "Power Pop",
    "Glam",
    "Spoken Word",
    "Modern Classical",
    "Bop",
    "Hard House",
    "Goth Rock",
    "Salsa",
    "New Age",
    "Jazz-Rock",
    "Conscious",
    "Bolero",
    "Free Improvisation",
    "Trip Hop",
    "Italo-Disco",
    "Latin Jazz",
    "Musical",
    "Emo",
    "Stoner Rock",
    "EBM",
    "Hard Bop",
    "Garage House",
    "Cumbia",
    "Free Jazz",
    "Surf",
    "Shoegaze",
    "MPB",
    "Jungle",
    "Doo Wop",
    "Oi",
    "J-pop",
    "Field Recording",
    "Cool Jazz",
    "Story",
    "Contemporary R&B",
    "Happy Hardcore",
    "Samba",
    "UK Garage",
    "Hardstyle",
    "Post Bop",
    "Tribal",
    "Volksmusik",
    "Bluegrass",
    "Tango",
    "Laïkó",
    "Celtic",
    "Radioplay",
    "Pop Punk",
    "Darkwave",
    "Novelty",
    "Smooth Jazz",
    "Italodance",
    "Eurodance",
    "Synthwave",
    "Vaporwave",
    "Grunge",
    "Polka",
    "Flamenco",
    "Dixieland",
    "Future Jazz",
    "Arena Rock",
    "Symphonic Rock",
    "Latin",
    "Southern Rock",
    "Metalcore",
    "Parody",
    "Hardcore Hip-Hop",
    "Glitch",
    "Nu Metal",
    "Choral",
    "AOR",
    "Hindustani",
    "Progressive Metal",
    "Rumba",
    "Gabber",
    "Space Rock",
    "Krautrock",
    "Trap",
    "Cha-Cha",
    "Hi NRG",
    "Dub Techno",
    "Thug Rap",
    "Speed Metal",
    "Bossa Nova",
    "Breakcore",
    "Power Metal",
    "Merengue",
    "Acid House",
    "Reggae-Pop",
    "Audiobook",
    "Bollywood",
    "Power Electronics",
    "Poetry",
    "Neo-Classical",
    "Musique Concrète",
    "Boom Bap",
    "Mod",
    "Freestyle",
    "Electric Blues",
    "Acid Jazz",
    "Harsh Noise Wall",
    "Boogie",
    "Bossanova",
    "Avant-garde Jazz",
    "Jazzy Hip-Hop",
    "Country Blues",
    "Renaissance",
    "Big Beat",
    "Chiptune",
    "Mambo",
    "Tribal House",
    "Marches",
    "Interview",
    "Sludge Metal",
    "Bass Music",
    "Post-Hardcore",
    "Math Rock",
    "Broken Beat",
    "Rocksteady",
    "Chicago Blues",
    "Calypso",
    "Modal",
    "Kayōkyoku",
    "Ranchera",
    "Neofolk",
    "Dungeon Synth",
    "Ethereal",
    "Minimal Techno",
    "Psychedelic",
    "Education",
    "Afrobeat",
    "Indian Classical",
    "Grime",
    "Lounge",
    "Afro-Cuban",
    "Nu-Disco",
    "Goa Trance",
    "Neo Soul",
    "Hip-House",
    "Light Music",
    "Lovers Rock",
    "Crust",
    "Ragtime",
    "Éntekhno",
    "Berlin-School",
    "Guaracha",
    "Impressionist",
    "Rhythmic Noise",
    "Psychobilly",
    "G-Funk",
    "Operetta",
    "Gothic Metal",
    "Cut-up/DJ",
    "Euro-Disco",
    "Ragga",
    "Nursery Rhymes",
    "Pacific",
    "Brass Band",
    "Neo-Romantic",
    "Medieval",
    "Chillwave",
    "Tech Trance",
    "Dialogue",
    "Speedcore",
    "Ragga HipHop",
    "Britpop",
    "Son",
    "Guaguancó",
    "Symphonic Metal",
    "Space-Age",
    "Canzone Napoletana",
    "Twist",
    "Melodic Death Metal",
    "Deep Techno",
    "Honky Tonk",
    "Promotional",
    "Mandopop",
    "Fado",
    "Eurobeat",
    "Nordic",
    "Educational",
    "Goregrind",
    "Funk Metal",
    "Political",
    "Music Hall",
    "Video Game Music",
    "Highlife",
    "Military",
    "Makina",
    "Acid Rock",
    "Melodic Hardcore",
    "Soca",
    "Jazzdance",
    "Afro-Cuban Jazz",
    "Hard Techno",
    "Zouk",
    "New Jack Swing",
    "Speech",
    "Soukous",
    "Monolog",
    "Mariachi",
    "Folk Metal",
    "Piano Blues",
    "Delta Blues",
    "Dream Pop",
    "Atmospheric Black Metal",
    "Sound Collage",
    "Deathcore",
    "Modern Electric Blues",
    "Hawaiian",
    "New Beat",
    "Romani",
    "Horrorcore",
    "Brit Pop",
    "K-pop",
    "Cubano",
    "Reggaeton",
    "Viking Metal",
    "Gypsy Jazz",
    "Hands Up",
    "Jumpstyle",
    "Witch House",
    "Noisecore",
    "Luk Thung",
    "Public Broadcast",
    "Texas Blues",
    "Bubblegum",
    "Boogaloo",
    "Harmonica Blues",
    "Italo House",
    "Speed Garage",
    "Forró",
    "Freetekno",
    "Special Effects",
    "No Wave",
    "Cajun",
    "Coldwave",
    "Post-Metal",
    "Post-Modern",
    "Therapy",
    "P.Funk",
    "Pub Rock",
    "Norteño",
    "Sound Art",
    "City Pop",
    "Jump Blues",
    "Enka",
    "Illbient",
    "Oratorio",
    "Vallenato",
    "J-Rock",
    "Descarga",
    "Pachanga",
    "Yé-Yé",
    "Bassline",
    "Rebetiko",
    "Hillbilly",
    "Porro",
    "Bhangra",
    "Corrido",
    "Louisiana Blues",
    "Boogie Woogie",
    "Guajira",
    "Tejano",
    "Screw",
    "Beguine",
    "Donk",
    "Son Montuno",
    "Electroacoustic",
    "Min'yō",
    "Karaoke",
    "Juke",
    "Nueva Cancion",
    "Charanga",
    "Deathrock",
    "Raï",
    "Séga",
    "Depressive Black Metal",
    "Klezmer",
    "Cloud Rap",
    "Western Swing",
    "Sermon",
    "Technical",
    "Ghetto",
    "Crunk",
    "Power Violence",
    "DJ Battle Tool",
    "Chinese Classical",
    "Compas",
    "Copla",
    "Technical Death Metal",
    "Industrial Metal",
    "Aboriginal",
    "Népzene",
    "Disco Polo",
    "Swingbeat",
    "Tropical House",
    "Cantopop",
    "Groove Metal",
    "Electroclash",
    "Andean Music",
    "Bounce",
    "Free Funk",
    "Danzon",
    "Bayou Funk",
    "Bachata",
    "Zydeco",
    "Batucada",
    "Health-Fitness",
    "Funeral Doom Metal",
    "Pasodoble",
    "Turntablism",
    "Appalachian Music",
    "Halftime",
    "Conjunto",
    "Minneapolis Sound",
    "Catalan Music",
    "Quechua",
    "Sea Shanties",
    "Pornogrind",
    "Carnatic",
    "Movie Effects",
    "Música Criolla",
    "Steel Band",
    "Skiffle",
    "Progressive Breaks",
    "Hokkien Pop",
    "Lambada",
    "Levenslied",
    "Swamp Pop",
    "Early",
    "Ghetto House",
    "Miami Bass",
    "Jangle Pop",
    "Doomcore",
    "Sound Poetry",
    "Pipe & Drum",
    "Liscio",
    "J-Core",
    "Cretan",
    "Bleep",
    "Axé",
    "Footwork",
    "Plena",
    "Gamelan",
    "Ethno-pop",
    "Schranz",
    "Indo-Pop",
    "Britcore",
    "Ottoman Classical",
    "Baião",
    "Nueva Trova",
    "Persian Classical",
    "Horror Rock",
    "Mizrahi",
    "Erotic",
    "Choro",
    "Kwaito",
    "Glitch Hop",
    "Zarzuela",
    "Trova",
    "Musette",
    "Barbershop",
    "Ghazal",
    "Public Service Announcement",
    "Basque Music",
    "Go-Go",
    "Samba-Canção",
    "UK Street Soul",
    "Zamba",
    "Dangdut",
    "Group Sounds",
    "East Coast Blues",
    "Chamamé",
    "Memphis Blues",
    "Beatdown",
    "Luk Krung",
    "Tamil Film Music",
    "NDW",
    "Chacarera",
    "Andalusian Classical",
    "Twelve-tone",
    "Ghettotech",
    "Kaseko",
    "Bengali Music",
    "Reggae Gospel",
    "Neo Trance",
    "Joropo",
    "Qawwali",
    "Mo Lam",
    "Chutney",
    "Gaita",
    "Dub Poetry",
    "Hyphy",
    "Hiplife",
    "K-Rock",
    "Marimba",
    "Timba",
    "Huayno",
    "Rock Opera",
    "Piedmont Blues",
    "Cape Jazz",
    "UK Funky",
    "Gogo",
    "Keroncong",
    "Mento",
    "Cabaret",
    "Morna",
    "Favela Funk",
    "Guarania",
    "Baltimore Club",
    "Ryūkōka",
    "Medical",
    "Overtone Singing",
    "Nhạc Vàng",
    "Sephardic",
    "Jibaro",
    "Phleng Phuea Chiwit",
    "Jota",
    "Maloya",
    "Salegy",
    "Griot",
    "Phonk",
    "Hard Beat",
    "Lento Violento",
    "Thai Classical",
    "Beatbox",
    "Mugham",
    "Serial",
    "Marcha Carnavalesca",
    "Dark Jazz",
    "Gagaku",
    "Skweee",
    "Villancicos",
    "Bomba",
    "Mbalax",
    "Nerdcore Techno",
    "Balearic",
    "Galician Traditional",
    "Cuatro",
    "Funaná",
    "Sámi Music",
    "Candombe",
    "Sertanejo",
    "Hyperpop",
    "Sonero",
    "Carimbó",
    "Kizomba",
    "Ballroom",
    "Champeta",
    "Vaudeville",
    "Aguinaldo",
    "Stride",
    "Shaabi",
    "Break-In",
    "Spirituals",
    "Electro Swing",
    "Zemer Ivri",
    "Seresta",
    "Jug Band",
    "Philippine Classical",
    "Yemenite Jewish",
    "Junkanoo",
    "Funkot",
    "Mouth Music",
    "Rune Singing",
    "Caipira",
    "Jersey Club",
    "Néo Kyma",
    "Bambuco",
    "Cobla",
    "Gwo Ka",
    "Hill Country Blues",
    "Moombahton",
    "Piobaireachd",
    "Taarab",
    "Occitan",
    "Korean Court Music",
    "Progressive Bluegrass",
    "Rapso",
    "Bubbling",
    "Filk",
    "Waiata",
    "Cambodian Classical",
    "Bangladeshi Classical",
    "Lao Music",
    "Guggenmusik",
    "Rōkyoku",
    "Klasik",
    "Għana",
    "Bongo Flava",
    "Baroque Pop",
    "Gqom",
    "Motswako",
    "Spaza",
    "Milonga",
    "Kuduro",
    "Azonto",
    "Shidaiqu",
    "Sean-nós",
    "Shoegazer",
    "Trallalero"
];

// TODO: fetch styles from the backend server